/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho02;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author gusta
 */
public class JFrameCriarItem extends javax.swing.JDialog {

    /**
     * Creates new form JFrameCriarServidor
     */
    private ServidorDAO SDAO = new ServidorDAO();
    private AmbienteDAO ADAO = new AmbienteDAO();
    private ItemDAO IDAO = new ItemDAO();

    public JFrameCriarItem() {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        acbox.setEnabled(false);
        acbox.setModel(new DefaultComboBoxModel<>());
        scbox.setModel(new DefaultComboBoxModel<>());
        acbox.addItem("Escolha Ambiente");
        scbox.addItem("Escolha Servidor");
        List<Object> Servidor = SDAO.listar();
        for (Object s : Servidor) {
            scbox.addItem(s);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        iespecificacao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        iestado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        acbox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        aclear = new javax.swing.JButton();
        aconfirm = new javax.swing.JButton();
        acancel = new javax.swing.JButton();
        scbox = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        icodpatrimonio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        idatacompra = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        ivalorcompra = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setText("Especificação:");

        jLabel2.setText("Estado:");

        jLabel3.setText("Ambiente:");

        acbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Servidor:");

        aclear.setText("Limpar");
        aclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aclearActionPerformed(evt);
            }
        });

        aconfirm.setText("Confirmar");
        aconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aconfirmActionPerformed(evt);
            }
        });

        acancel.setText("Cancelar");
        acancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acancelActionPerformed(evt);
            }
        });

        scbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scboxActionPerformed(evt);
            }
        });

        jLabel5.setText("Cod. Patrimônio:");

        jLabel6.setText("Valor de Compra:");

        jLabel11.setText("Data de Compra:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(iestado, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(icodpatrimonio, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(idatacompra, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(acbox, 0, 321, Short.MAX_VALUE)
                            .addComponent(scbox, 0, 321, Short.MAX_VALUE)
                            .addComponent(ivalorcompra)
                            .addComponent(iespecificacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(acancel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aclear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(iespecificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(icodpatrimonio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(ivalorcompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idatacompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(scbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(acbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aclear)
                    .addComponent(aconfirm)
                    .addComponent(acancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aclearActionPerformed
        // TODO add your handling code here:
        iespecificacao.setText("");
        iestado.setText("");
        icodpatrimonio.setText("");
        ivalorcompra.setText("");
        idatacompra.setText("");
        scbox.setSelectedIndex(0);
        acbox.setSelectedIndex(0);
    }//GEN-LAST:event_aclearActionPerformed

    private void aconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aconfirmActionPerformed
        // TODO add your handling code here:
        Item i = new Item();
        i.setEspecificacao(iespecificacao.getText());
        Ambiente a = (Ambiente) acbox.getSelectedItem();
        i.setAmbiente(a);
        a.setData_modificacao(LocalDate.now());
        ADAO.alterar(a);
        Servidor s = (Servidor) scbox.getSelectedItem();
        i.setDono(s);
        i.setData_compra(LocalDate.parse(idatacompra.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        i.setCod_partimonio(Integer.parseInt(icodpatrimonio.getText()));
        i.setData_criacao(LocalDate.now());
        i.setData_modificacao(LocalDate.now());
        i.setEstado(Integer.parseInt(iestado.getText()));
        i.setValor_compra(Double.parseDouble(ivalorcompra.getText()));
        i = (Item) IDAO.adiciona(i);

        this.dispose();
    }//GEN-LAST:event_aconfirmActionPerformed

    private void acancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_acancelActionPerformed

    private void scboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scboxActionPerformed
        // TODO add your handling code here:
        if (scbox.getSelectedIndex() != 0) {
            acbox.setEnabled(true);
            acbox.removeAllItems();
            Servidor s = (Servidor) scbox.getSelectedItem();
            List<Object> Ambiente = ADAO.listar();
            for (Object a : Ambiente) {
                Ambiente a1 = (Ambiente) a;
                if (a1.getServidor().getId() == s.getId()) {
                    acbox.addItem(a);
                }
            }

        }


    }//GEN-LAST:event_scboxActionPerformed

    private void acboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_acboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCriarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCriarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCriarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCriarItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCriarItem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acancel;
    private javax.swing.JComboBox acbox;
    private javax.swing.JButton aclear;
    private javax.swing.JButton aconfirm;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField icodpatrimonio;
    private javax.swing.JTextField idatacompra;
    private javax.swing.JTextField iespecificacao;
    private javax.swing.JTextField iestado;
    private javax.swing.JTextField ivalorcompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JComboBox scbox;
    // End of variables declaration//GEN-END:variables
}
