/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalho02;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author gusta
 */
public class JFrameAlterarAmbiente extends javax.swing.JDialog {

    /**
     * Creates new form JFrameCriarServidor
     */
    private ServidorDAO SDAO = new ServidorDAO();
    private CampusDAO CDAO = new CampusDAO();
    private AmbienteDAO ADAO = new AmbienteDAO();
    private static Ambiente a;
    private List<Servidor> Servidor = (List) SDAO.listar();

    public JFrameAlterarAmbiente(Ambiente a) {
        initComponents();
        setLocationRelativeTo(null);
        setModal(true);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        this.a = a;
        ccbox.setModel(new DefaultComboBoxModel<>());
        List<Object> Campus = CDAO.listar();
        for (Object c : Campus) {
            ccbox.addItem(c);
            Campus c1 = (Campus) c;
            if (a.getCampus().getId() == c1.getId()) {
                ccbox.setSelectedItem(c);
            }
        }

        scbox.setModel(new DefaultComboBoxModel<>());
        scbox.addItem("Escolha Servidor");

        Campus c = (Campus) ccbox.getSelectedItem();
        scbox.setModel(new DefaultComboBoxModel<>());
        scbox.addItem("Escolha Servidor");
        for (Servidor s : Servidor) {
            if (c.getId() == s.getCampus().getId()) {
                scbox.addItem(s);
                if (a.getServidor().getId() == s.getId()) {
                    scbox.setSelectedItem(s);
                }

            }
        }

        adescricao.setText(a.getDescricao());
        adatacriacao.setText(a.getData_criacao().format(DateTimeFormatter.ofPattern("dd/MM/yyyy")));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        adescricao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        adatacriacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ccbox = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        aclear = new javax.swing.JButton();
        aconfirm = new javax.swing.JButton();
        acancel = new javax.swing.JButton();
        scbox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));

        jLabel1.setText("Descrição:");

        jLabel2.setText("Data de Criação:");

        jLabel3.setText("Campus:");

        ccbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ccboxActionPerformed(evt);
            }
        });

        jLabel4.setText("Servidor:");

        aclear.setText("Limpar");
        aclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aclearActionPerformed(evt);
            }
        });

        aconfirm.setText("Confirmar");
        aconfirm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aconfirmActionPerformed(evt);
            }
        });

        acancel.setText("Cancelar");
        acancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acancelActionPerformed(evt);
            }
        });

        scbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scboxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ccbox, 0, 323, Short.MAX_VALUE)
                            .addComponent(scbox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(adescricao)
                            .addComponent(adatacriacao)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(acancel, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aclear, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(aconfirm, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(adescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ccbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(scbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(adatacriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aclear)
                    .addComponent(aconfirm)
                    .addComponent(acancel))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aclearActionPerformed
        // TODO add your handling code here:
        adescricao.setText("");
        adatacriacao.setText("");
        scbox.setSelectedIndex(0);
        ccbox.setSelectedIndex(0);
    }//GEN-LAST:event_aclearActionPerformed

    private void aconfirmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aconfirmActionPerformed
        // TODO add your handling code here:
        // for iterativo remover tudo do iabox

        a.setDescricao(adescricao.getText());
        Campus c = (Campus) ccbox.getSelectedItem();
        a.setCampus(c);
        Servidor s = (Servidor) scbox.getSelectedItem();
        a.setServidor(s);
        a.setData_criacao(LocalDate.parse(adatacriacao.getText(), DateTimeFormatter.ofPattern("dd/MM/yyyy")));
        a.setData_modificacao(LocalDate.now());
        a = (Ambiente) ADAO.alterar(a);

        this.dispose();
    }//GEN-LAST:event_aconfirmActionPerformed

    private void acancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acancelActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_acancelActionPerformed

    private void scboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_scboxActionPerformed

    private void ccboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ccboxActionPerformed
        // TODO add your handling code here:
        if (ccbox.hasFocus()) {
            Campus c1 = (Campus) ccbox.getSelectedItem();
            int tam = scbox.getItemCount() - 1;
            for (int i = 0; i < tam; i++) {
                scbox.removeItemAt(1);
            }
            for (Servidor s : Servidor) {
                if (s.getCampus().getId() == c1.getId()) {
                    scbox.addItem(s);
                }
            }
        }
    }//GEN-LAST:event_ccboxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameAlterarAmbiente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarAmbiente(a).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton acancel;
    private javax.swing.JButton aclear;
    private javax.swing.JButton aconfirm;
    private javax.swing.JTextField adatacriacao;
    private javax.swing.JTextField adescricao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox ccbox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JComboBox scbox;
    // End of variables declaration//GEN-END:variables
}
